import ActionType from "./action-types";

// SET_ALERT 
// REMOVE_ALERT 

// REGISTER_SUCCESS 
// REGISTER_FAIL 
// USER_LOADED 
// AUTH_ERROR 

// LOGIN_REQUEST 
// LOGIN_SUCCESS 
// LOGIN_FAIL 
// LOGOUT 

// GET_PROFILE 
// GET_PROFILES 
// UPDATE_PROFILE 
// CLEAR_PROFILE 
// PROFILE_ERROR 

// GET_REPOS 
// NO_REPOS 



// ACCOUNT_DELETED 
// GET_POSTS 
// GET_POST 
// POST_ERROR 
// UPDATE_LIKES 
// DELETE_POST 
// ADD_POST 
// ADD_COMMENT 
// REMOVE_COMMENT 

// USER_DETAILS_REQUEST 
// USER_DETAILS_SUCCESS 
// USER_DETAILS_FAIL 
// USER_DETAILS_RESET 

// USER_LIST_REQUEST 
// USER_LIST_SUCCESS 
// USER_LIST_FAIL 
// USER_UPDATE_RESET 

// USER_DELETE_REQUEST 
// USER_DELETE_SUCCESS 
// USER_DELETE_FAIL 

// USER_SIGNIN_REQUEST 
// USER_SIGNIN_SUCCESS 
// USER_SIGNIN_FAIL 
// USER_SIGNOUT 


// PAYMENT_REQUEST 
// PAYMENT_SUCCESS 
// PAYMENT_FAIL 

// GET_PAYMENT 
// GET_PAYMENTS 
// GET_PAYMENTS_FAIL
// DELETE_PAYMENT
// DELETE_PAYMENT_FAIL 
// ADD_PAYMENT 
// REMOVE_PAYMENT 

// DIFFICULTY_LEVEL_REQUEST 
// DIFFICULTY_LEVEL_SUCCESS 
// DIFFICULTY_LEVEL_FAIL 
// ADD_DIFFICULTY_LEVEL 
// DIFFICULTY_LEVEL_LOADED 

// SUBJECT_REQUEST 
// SUBJECT_SUCCESS 
// SUBJECT_FAIL 
// SUBJECT_LOADED 

// TESTS_REQUEST 
// TESTS_SUCCESS 
// TESTS_FAIL 
// TESTS_LOADED 

// TOPIC_REQUEST 
// TOPIC_SUCCESS 
// TOPIC_FAIL 
// TOPIC_LOADED

// USER_PERFORMANCE_REQUEST 
// USER_PERFORMANCE_SUCCESS 
// USER_PERFORMANCE_FAIL 
// USER_PERFORMANCE_LOADED 

// QUESTION_REQUEST 
// QUESTION_SUCCESS 
// QUESTION_FAIL 
// QUESTION_LOADED 

// FIND_QUESTION_REQUEST 
// FIND_QUESTION_SUCCESS 
// FIND_QUESTION_FAIL 
// FIND_QUESTION_LOADED 

// STU_TESTS_REQUEST 
// STU_TESTS_SUCCESS 
// STU_TESTS_FAIL 
// STU_TESTS_LOADED 

// UNIC_TOPIC_REQUEST 
// UNIC_TOPIC_SUCCESS 
// UNIC_TOPIC_FAIL 
// UNIC_TOPIC_LOADED 

// UNIC_DIFFICULTY_LEVEL_REQUEST 
// UNIC_DIFFICULTY_LEVEL_SUCCESS 
// UNIC_DIFFICULTY_LEVEL_FAIL 
// UNIC_ADD_DIFFICULTY_LEVEL 
// UNIC_DIFFICULTY_LEVEL_LOADED 

// SELECTED_QUESTION_REQUEST 
// SELECTED_QUESTION_SUCCESS 
// SELECTED_QUESTION_FAIL 
// SELECTED_QUESTION_LOADED 

// UNIC_SUBJECT_REQUEST 
// UNIC_SUBJECT_SUCCESS 
// UNIC_SUBJECT_FAIL 
// UNIC_SUBJECT_LOADED 

// COUNTED_QUESTION_REQUEST 
// COUNTED_QUESTION_SUCCESS 
// COUNTED_QUESTION_FAIL 
// COUNTED_QUESTION_LOADED 

// ONE_PERFORMANCE_REQUEST
// ONE_PERFORMANCE_SUCCESS 
// ONE_PERFORMANCE_FAIL  
// ONE_PERFORMANCE_LOADED  

// POST_QUESTION_REQUEST  
// POST_QUESTION_SUCCESS  
// POST_QUESTION_FAIL  

// PUT_TEST_REQUEST  
// PUT_TEST_SUCCESS  
// PUT_TEST_FAIL  

// SCORE_TEST_REQUEST 
// SCORE_TEST_SUCCESS  
// SCORE_TEST_FAIL  

// SCORE_QUESTION_REQUEST  
// SCORE_QUESTION_SUCCESS  
// SCORE_QUESTION_FAIL  

// OVERALL_SCORE_QUESTION_REQUEST  
// OVERALL_SCORE_QUESTION_SUCCESS  
// OVERALL_SCORE_QUESTION_FAIL 

// DELETE_CANDIDATE_TESTS_REQUEST  
// DELETE_CANDIDATE_TESTS_SUCCESS  
// DELETE_CANDIDATE_TESTS_FAIL  

// USER_UPDATE_REQUEST  
// USER_UPDATE_SUCCESS  
// USER_UPDATE_FAIL   

// EACH_TOPIC_REQUEST  
// EACH_TOPIC_SUCCESS  
// EACH_TOPIC_FAIL  

// SELECTED_TEST_REQUEST  
// SELECTED_TEST_SUCCESS 
// SELECTED_TEST_FAIL  
// SELECTED_TEST_LOADED  

// TESTS_UNMARKED_REQUEST  
// TESTS_UNMARKED_SUCCESS  
// TESTS_UNMARKED_FAIL 
// TESTS_UNMARKED_LOADED  
