export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET ';

//USER_LIST_REQUEST layout/USER_DELETE_REQUEST
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

//USER_SIGNOUT
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

//USER_LIST_REQUEST layout/USER_DELETE_REQUEST  REMOVE_PAYMENT
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';

export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const GET_PAYMENTS_FAIL = 'GET_PAYMENTS_FAIL';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT';

export const DIFFICULTY_LEVEL_REQUEST = 'DIFFICULTY_LEVEL_REQUEST';
export const DIFFICULTY_LEVEL_SUCCESS = 'DIFFICULTY_LEVEL_SUCCESS';
export const DIFFICULTY_LEVEL_FAIL = 'DIFFICULTY_LEVEL_FAIL';
export const ADD_DIFFICULTY_LEVEL = 'GET_DIFFICULTY_LEVEL';
export const DIFFICULTY_LEVEL_LOADED = 'DIFFICULTY_LEVEL_LOADED';

export const SUBJECT_REQUEST = 'SUBJECT_REQUEST';
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';
export const SUBJECT_FAIL = 'SUBJECT_FAIL';
export const SUBJECT_LOADED = 'SUBJECT_LOADED';

export const TESTS_REQUEST = 'TESTS_REQUEST';
export const TESTS_SUCCESS = 'TESTS_SUCCESS';
export const TESTS_FAIL = 'TESTS_FAIL';
export const TESTS_LOADED = 'TESTS_LOADED';

export const TOPIC_REQUEST = 'TOPIC_REQUEST';
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS';
export const TOPIC_FAIL = 'TOPIC_FAIL';
export const TOPIC_LOADED = 'TOPIC_LOADED';

export const USER_PERFORMANCE_REQUEST = 'USER_PERFORMANCE_REQUEST';
export const USER_PERFORMANCE_SUCCESS = 'USER_PERFORMANCE_SUCCESS';
export const USER_PERFORMANCE_FAIL = 'USER_PERFORMANCE_FAIL';
export const USER_PERFORMANCE_LOADED = 'USER_PERFORMANCE_LOADED';

export const QUESTION_REQUEST = 'QUESTION_SUCCESS_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_FAIL = 'QUESTION_FAIL';
export const QUESTION_LOADED = 'QUESTION_LOADED';

export const FIND_QUESTION_REQUEST = 'FIND_QUESTION_SUCCESS_REQUEST';
export const FIND_QUESTION_SUCCESS = 'FIND_QUESTION_SUCCESS';
export const FIND_QUESTION_FAIL = 'FIND_QUESTION_FAIL';
export const FIND_QUESTION_LOADED = 'FIND_QUESTION_LOADED';

export const STU_TESTS_REQUEST = 'STU_TESTS_REQUEST';
export const STU_TESTS_SUCCESS = 'STU_TESTS_SUCCESS';
export const STU_TESTS_FAIL = 'STU_TESTS_FAIL';
export const STU_TESTS_LOADED = 'STU_TESTS_LOADED';

export const UNIC_TOPIC_REQUEST = 'UNIC_TOPIC_REQUEST';
export const UNIC_TOPIC_SUCCESS = 'UNIC_TOPIC_SUCCESS';
export const UNIC_TOPIC_FAIL = 'UNIC_TOPIC_FAIL';
export const UNIC_TOPIC_LOADED = 'UNIC_TOPIC_LOADED';

export const UNIC_DIFFICULTY_LEVEL_REQUEST = 'UNIC_DIFFICULTY_LEVEL_REQUEST';
export const UNIC_DIFFICULTY_LEVEL_SUCCESS = 'UNIC_DIFFICULTY_LEVEL_SUCCESS';
export const UNIC_DIFFICULTY_LEVEL_FAIL = 'UNIC_DIFFICULTY_LEVEL_FAIL';
export const UNIC_ADD_DIFFICULTY_LEVEL = 'UNIC_GET_DIFFICULTY_LEVEL';
export const UNIC_DIFFICULTY_LEVEL_LOADED = 'UNIC_DIFFICULTY_LEVEL_LOADED';

export const SELECTED_QUESTION_REQUEST = 'SELECTED_QUESTION_SUCCESS_REQUEST';
export const SELECTED_QUESTION_SUCCESS = 'SELECTED_QUESTION_SUCCESS';
export const SELECTED_QUESTION_FAIL = 'SELECTED_QUESTION_FAIL';
export const SELECTED_QUESTION_LOADED = 'SELECTED_QUESTION_LOADED';

export const UNIC_SUBJECT_REQUEST = 'UNIC_SUBJECT_REQUEST';
export const UNIC_SUBJECT_SUCCESS = 'UNIC_SUBJECT_SUCCESS';
export const UNIC_SUBJECT_FAIL = 'UNIC_SUBJECT_FAIL';
export const UNIC_SUBJECT_LOADED = 'UNIC_SUBJECT_LOADED';

export const COUNTED_QUESTION_REQUEST = 'COUNTED_QUESTION_SUCCESS_REQUEST';
export const COUNTED_QUESTION_SUCCESS = 'COUNTED_QUESTION_SUCCESS';
export const COUNTED_QUESTION_FAIL = 'COUNTED_QUESTION_FAIL';
export const COUNTED_QUESTION_LOADED = 'COUNTED_QUESTION_LOADED';

export const ONE_PERFORMANCE_REQUEST = 'ONE_PERFORMANCE_REQUEST';
export const ONE_PERFORMANCE_SUCCESS = 'ONE_PERFORMANCE_SUCCESS';
export const ONE_PERFORMANCE_FAIL = 'ONE_PERFORMANCE_FAIL';
export const ONE_PERFORMANCE_LOADED = 'ONE_PERFORMANCE_LOADED';

export const POST_QUESTION_REQUEST = 'POST_QUESTION_REQUEST';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAIL = 'POST_QUESTION_FAIL';

export const PUT_TEST_REQUEST = 'PUT_TEST_REQUEST';
export const PUT_TEST_SUCCESS = 'PUT_TEST_SUCCESS';
export const PUT_TEST_FAIL = 'PUT_TEST_FAIL';

export const SCORE_TEST_REQUEST = 'SCORE_TEST_REQUEST';
export const SCORE_TEST_SUCCESS = 'SCORE_TEST_SUCCESS';
export const SCORE_TEST_FAIL = 'SCORE_TEST_FAIL';

export const SCORE_QUESTION_REQUEST = 'SCORE_QUESTION_REQUEST';
export const SCORE_QUESTION_SUCCESS = 'SCORE_QUESTION_SUCCESS';
export const SCORE_QUESTION_FAIL = 'SCORE_QUESTION_FAIL';

export const OVERALL_SCORE_QUESTION_REQUEST = 'OVERALL_SCORE_QUESTION_REQUEST';
export const OVERALL_SCORE_QUESTION_SUCCESS = 'OVERALL_SCORE_QUESTION_SUCCESS';
export const OVERALL_SCORE_QUESTION_FAIL = 'OVERALL_SCORE_QUESTION_FAIL';

export const DELETE_CANDIDATE_TESTS_REQUEST = 'DELETE_CANDIDATE_TESTS_REQUEST';
export const DELETE_CANDIDATE_TESTS_SUCCESS = 'DELETE_CANDIDATE_TESTS_SUCCESS';
export const DELETE_CANDIDATE_TESTS_FAIL = 'DELETE_CANDIDATE_TESTS_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const EACH_TOPIC_REQUEST = 'EACH_TOPIC_REQUEST';
export const EACH_TOPIC_SUCCESS = 'EACH_TOPIC_SUCCESS';
export const EACH_TOPIC_FAIL = 'EACH_TOPIC_FAIL';

export const SELECTED_TEST_REQUEST = 'SELECTED_TEST_SUCCESS_REQUEST';
export const SELECTED_TEST_SUCCESS = 'SELECTED_TEST_SUCCESS';
export const SELECTED_TEST_FAIL = 'SELECTED_TEST_FAIL';
export const SELECTED_TEST_LOADED = 'SELECTED_TEST_LOADED';
